# Generated by Django 4.1.1 on 2022-10-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(max_length=50)),
                ('poles_r', models.IntegerField(null=True)),
                ('poles_y', models.IntegerField(null=True)),
                ('poles_b', models.IntegerField(null=True)),
                ('group', models.CharField(max_length=50, null=True)),
                ('period_type', models.CharField(default='Fixed', max_length=10)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('sunrise_offset', models.IntegerField(null=True)),
                ('sunset_offset', models.IntegerField(null=True)),
                ('on_time', models.TimeField(default='18:00:00')),
                ('off_time', models.TimeField(default='06:00:00')),
                ('is_on', models.BooleanField(default=0)),
                ('is_change', models.BooleanField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetersThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=20)),
                ('field_name', models.CharField(max_length=3)),
                ('unit', models.CharField(max_length=3)),
                ('min_thr', models.FloatField()),
                ('max_thr', models.FloatField()),
                ('notify', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_r', models.FloatField()),
                ('v_y', models.FloatField()),
                ('v_b', models.FloatField()),
                ('c_r', models.FloatField()),
                ('c_y', models.FloatField()),
                ('c_b', models.FloatField()),
                ('p_r', models.FloatField()),
                ('p_y', models.FloatField()),
                ('p_b', models.FloatField()),
                ('pf', models.FloatField()),
                ('kvar', models.FloatField()),
                ('freq', models.FloatField()),
                ('kwh', models.FloatField()),
                ('kvah', models.FloatField()),
                ('inserted_on', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Faults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_desc', models.CharField(max_length=100)),
                ('fault_loc', models.CharField(max_length=50)),
                ('r_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('seen_report', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meter')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
