# Generated by Django 4.1.1 on 2023-02-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_devicedata_inserted_on_devicedatalog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_change',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='device',
            name='off_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='on_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sunrise_offset',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sunset_offset',
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
    ]
